# -*- coding: utf-8 -*-
"""ScrapeFrames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0p65x4fQNjfGMCBYsEu9r1J97duPj8a
"""

import pandas as pd
import os
import subprocess
!pip install youtube-dl
!pip install ffmpeg-python
!pip install pytube

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/236/train.csv', header=None)
# print(df.head())
youtube_urls = df[5].tolist()
youtube_urls = youtube_urls[1:]
video_ids = df[0].tolist()[1:]
print(video_ids)

frames_directory = '/content/drive/My Drive/236/frames'
os.makedirs(frames_directory, exist_ok=True)

def download_video(url, path):
    try:
        yt = YouTube(url)
        yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download(output_path='', filename=path)
        return True
    except Exception as e:
        print(f"Error downloading {url}: {e}")
        return False

# Download each video and extract the first frame
for url, video_id in zip(youtube_urls, video_ids):
    video_path = f'/content/video_{video_id}.mp4'
    frame_path = os.path.join(frames_directory, f'frame_{video_id}.jpg')

    # Download video using pytube
    if download_video(url, video_path):
        # Extract the first frame using ffmpeg
        subprocess.run(['ffmpeg', '-i', video_path, '-frames:v', '1', frame_path])

        if os.path.exists(video_path):
            os.remove(video_path)
